[package]
name = "iec104-client"
version = "0.1.0"
authors = ["Daniel Teunis <daniel@teunis.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
